---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-system
  labels:
    name: vault-system
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    istio-injection: enabled
