---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault-secrets-webhook
  namespace: vault-system
spec:
  releaseName: vault-secrets-webhook  
  chart:
    repository: https://kubernetes-charts.banzaicloud.com/
    name: vault-secrets-webhook
    version: 1.0.0
  values:
    {}
---
  apiVersion: helm.fluxcd.io/v1
  kind: HelmRelease
  metadata:
    name: vault-operator
    namespace: vault-system
  spec:
    releaseName: vault-operator  
    chart:
      repository: https://kubernetes-charts.banzaicloud.com/
      name: vault-operator
      version: 1.0.0
    values:
      {}